In [1]:
import numpy as np
import pybullet as p

NUM_DRONES = 4
distWallRef = 0.5
SENSOR_ATTR = True
max_range = 3
if SENSOR_ATTR :
    sensor_position =np.zeros((4,3)) 
    print(sensor_position)  # questo è lo zero del mondo
    sensor_direction = np.array([
    [1.0, 0.0, 0.0],  # front
    [0.0, 1.0, 0.0],  # Rx
    [-1.0, 0.0, 0.0],   # behind
    [0.0, -1.0, 0.0],  # Lx
    ])
    rot_mat = np.array([      # rot mat esempio SOTTO come estrarla veramente
    [0.866, -0.5, 0.0],
    [0.5, 0.866, 0.0],
    [0.0, 0.0, 1.0]
    ])
    # rot_mat = np.array(p.getMatrixFromQuaternion(quat[nth_drone, :])).reshape(3, 3)
    sensor_direction = np.dot(sensor_direction,rot_mat)   # (3, 3) * () 
    print(sensor_direction)

    observation = np.array([[max_range,max_range,max_range,max_range] for j in range(NUM_DRONES)] )
    print(observation)

def _sensorsObs():
        # observation = np.array([[max_range,max_range,max_range,max_range] for j in range(NUM_DRONES)] )
        Hit_point = []
        if SENSOR_ATTR:
            for i in range(NUM_DRONES):
                closest_hit = []
                for j in range(NUM_SENSORS) :
                    sensor_position = _getDroneStateVector(i)[0:3]  # piazza il sensore nella posiz attuale
                    from_positions = [sensor_position] * 4
                    
                    to_positions = [sensor_position + sensor_direction * 3 for direction in directions.values()]
                  #  result = p.rayTest(sensor_position, 
                  #                      [sensor_position[0] + max_range[0] * sensor_direction[j][0], 
                  #                      sensor_position[1] + max_range[0] * sensor_direction[j][1], 
                  #                      sensor_position[2] + max_range[0] * sensor_direction[j][2]])
                    result = p.rayTestBatch(from_positions, to_positions)
                    closest_hit.append(result[0])
                        #closest_hit[j][0] = result_list[j][0]
                    # Se c'è un punto di contatto, ottieni la distanza
                    if closest_hit[j][0] != -1:
                        hit_distance = closest_hit[j][2]
                        hit_point = closest_hit[j][3]
                        # Aggiungi la distanza rilevata come osservazione
                        observation[i][j]= hit_distance
                        Hit_point.append(hit_point)
                    else:
                        # Se non ci sono oggetti rilevati, assegna una distanza massima
                        observation[i][j] =  self.max_range
                        Hit_point.append([])
        return observation, Hit_point

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.866 -0.5    0.   ]
 [ 0.5    0.866  0.   ]
 [-0.866  0.5    0.   ]
 [-0.5   -0.866  0.   ]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [8]:
max_range = 3
sensor_position = np.array([0. , 0. , 0.]) # piazza il sensore nella posiz attuale
print(sensor_position)
from_positions = [sensor_position] * 4
print(from_positions)
sensor_direction = [
    [1.0, 0.0, 0.0],  # front
    [0.0, 1.0, 0.0],  # Rx
    [-1.0, 0.0, 0.0],   # behind
    [0.0, -1.0, 0.0],  # Lx
    ]
sensor_direction = np.array(sensor_direction)   # converte in matrice numpy
rot_mat = np.array([      # rot mat esempio SOTTO come estrarla veramente
    [0.866, -0.5, 0.0],
    [0.5, 0.866, 0.0],
    [0.0, 0.0, 1.0]
    ])
    # rot_mat = np.array(p.getMatrixFromQuaternion(quat[nth_drone, :])).reshape(3, 3)
sensor_direction = np.dot(sensor_direction,rot_mat)   # (3, 3) * () 
print(sensor_direction)
from_positions = np.tile(sensor_position, (4, 1))
print(from_positions)
to_positions = np.array([sensor_position + direction * max_range for direction in sensor_direction])
print(to_positions)

[0. 0. 0.]
[array([0., 0., 0.]), array([0., 0., 0.]), array([0., 0., 0.]), array([0., 0., 0.])]
[[ 0.866 -0.5    0.   ]
 [ 0.5    0.866  0.   ]
 [-0.866  0.5    0.   ]
 [-0.5   -0.866  0.   ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 2.598 -1.5    0.   ]
 [ 1.5    2.598  0.   ]
 [-2.598  1.5    0.   ]
 [-1.5   -2.598  0.   ]]


In [16]:
import numpy as np### TEST PRODOTTO RXC ROTAZIONE
sensor_direction = np.array([
    [1.0, 0.0, 0.0],  # front
    [0.0, 1.0, 0.0],  # Rx
    [-1.0, 0.0, 0.0],   # behind
    [0.0, -1.0, 0.0],  # Lx
    ])
rot_mat = np.array([      # rot mat esempio SOTTO come estrarla veramente
    [0.866, -0.5, 0.0],
    [0.5, 0.866, 0.0],
    [0.0, 0.0, 1.0]
    ])
    # rot_mat = np.array(p.getMatrixFromQuaternion(quat[nth_drone, :])).reshape(3, 3)
sensor_direction = np.dot(sensor_direction,rot_mat)   # (3, 3) * ()
print(sensor_direction)

[[ 0.866 -0.5    0.   ]
 [ 0.5    0.866  0.   ]
 [-0.866  0.5    0.   ]
 [-0.5   -0.866  0.   ]]


In [8]:
import numpy as np
a=np.array([ 0 , 0 , 0 ])
print("a=",a)
print(a.shape)
b=np.array([ 0 , 0 , 0 ])
c = np.vstack((a, b))
print("c=",c)
print(c.shape)
d = np.hstack((a, b))
print("d=",d, "fatto male")
print(d.shape)
e = np.hstack((a[:, np.newaxis], b[:, np.newaxis]))
print("e=",e)
print(e.shape)
print("c e e sono uguali solo se il vettore era di 2 valori")

a= [0 0 0]
(3,)
c= [[0 0 0]
 [0 0 0]]
(2, 3)
d= [0 0 0 0 0 0] fatto male
(6,)
e= [[0 0]
 [0 0]
 [0 0]]
(3, 2)
c e e sono uguali solo se il vettore era di 2 valori


In [2]:
import numpy as np
NUM_DRONES = 3
NUM_SENSORS = 4
Hit_point = np.array([[[np.inf , np.inf , np.inf] for j in range(NUM_SENSORS)]for i in range(NUM_DRONES)] )
print(Hit_point)
hit_point = (1.0000000000000002, 0.0, 0.9998298611111112)
print(hit_point)
Hit_point[1][0] = hit_point
print(Hit_point)


[[[inf inf inf]
  [inf inf inf]
  [inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]
  [inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]
  [inf inf inf]
  [inf inf inf]]]
(1.0000000000000002, 0.0, 0.9998298611111112)
[[[       inf        inf        inf]
  [       inf        inf        inf]
  [       inf        inf        inf]
  [       inf        inf        inf]]

 [[1.         0.         0.99982986]
  [       inf        inf        inf]
  [       inf        inf        inf]
  [       inf        inf        inf]]

 [[       inf        inf        inf]
  [       inf        inf        inf]
  [       inf        inf        inf]
  [       inf        inf        inf]]]


In [5]:
import numpy as np
rR=1
rF=np.inf
alfa = np.arctan(rF/rR)  #arctan di inf fa pi/2
d = rF * np.cos(alfa)

print(alfa)
print(np.cos(alfa))
print(d)

1.5707963267948966
6.123233995736766e-17
inf


In [12]:
omega= 1
a = []
a.append(omega)
a.append(omega)
print(a)
b = []
np.vstack((b,omega))


[1, 1]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 0 and the array at index 1 has size 1

In [18]:
NUM_DRONES = 4
omega = np.array([[0.] for j in range(NUM_DRONES)])
sWF = [5 , 2]
cw = 0.03
print(omega      )

omega [1] = ([-1*sWF[1]*cw])
print(omega     )

[[0.]
 [0.]
 [0.]
 [0.]]
[[ 0.  ]
 [-0.06]
 [ 0.  ]
 [ 0.  ]]


In [3]:
import numpy as np
CLOUD_POINT = np.empty((3,0))
print(CLOUD_POINT)
print(CLOUD_POINT.shape)

PREV_DIST = np.array([[] for j in range(3)])
print(PREV_DIST)
print(PREV_DIST.shape)
PREV_DIST[2] =  ([0])
print(PREV_DIST)
print(PREV_DIST.shape)

[]
(3, 0)
[]
(3, 0)
[]
(3, 0)


In [27]:
NWdistance = np.inf
SWdistance =  np.inf
distance = min(NWdistance, SWdistance)
print(distance)
if distance == np.inf:
    print("daje")

inf
daje


In [28]:
import numpy as np
distance=np.array([[np.inf , np.inf] for j in range(1)] )
print(distance)

omega1 = np.array([0 , 0])
print(omega1)
print(omega1.shape)


[[inf inf]]
[0 0]
(2,)


In [40]:
Omega = ([3.])
print(Omega)


omega = np.array([[0.] for j in range(3)])
print(omega)
omega[1] = Omega
print(omega)
print(omega[1])


[3.0]
[[0.]
 [0.]
 [0.]]
[[0.]
 [3.]
 [0.]]
[3.]


In [41]:
# forse dovremmo fare così per quando sono liste di valori e non di vettori
Omega = ([3.])
print(Omega)


omega = np.array([0. for j in range(3)])
print(omega)
omega[1] = Omega[0]
print(omega)
print(omega[1])
#print(omega[1][0])

[3.0]
[0. 0. 0.]
[0. 3. 0.]
3.0


In [2]:
s_WF: int = -1
S_WF = np.array([[s_WF] for j in range(3)])
print(S_WF[1][0])
np.arctan(np.inf)

-1


1.5707963267948966

In [1]:
import numpy as np
distance=np.array([ [["droneID"]] , [[ 1. , 1. , 1.] for j in range(10)]  ])
print(distance)



ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [43]:


a = 13
print(a)
a = np.clip(a, -2., 2.)
print(a)
a[2] = np.clip(a[2], -0.15, .15)
print(a)

13
2.0


IndexError: invalid index to scalar variable.

In [1]:
import numpy as np
NUM_DRONES = 3 
wfstatezero_debugger = np.array([[0. , 0. , 0.] for j in range(NUM_DRONES)] )
print(wfstatezero_debugger)
wfstatezero_debugger[1] = [1. , 1. , 1.]
print(wfstatezero_debugger)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]


In [23]:
import numpy as np
NUM_DRONES = 4
#points_db = np.array([[[0. , 0. , 0.],[0.]] for j in range(NUM_DRONES)] )
points_db = [ [1, 1, [3.3, 2.1, 1.5], 'stringa'] for j in range(NUM_DRONES) ]
#points_db = np.hstack( [[1, 1, [3.3, 2.1, 1.5], 'stringa'] for j in range(NUM_DRONES)] )

print(points_db)

[[1, 1, [3.3, 2.1, 1.5], 'stringa'], [1, 1, [3.3, 2.1, 1.5], 'stringa'], [1, 1, [3.3, 2.1, 1.5], 'stringa'], [1, 1, [3.3, 2.1, 1.5], 'stringa']]


In [90]:
import numpy as np

drones_db = {
                1: {
                    '0001': {'coords': [3.0, 1.8, 1.0], 'type': 'junction'},
                    '0002': {'coords': [3.3, 2.3, 1.0], 'type': 'corridor'},
                    '0003': {'coords': [1.0, 1.0, 1.0], 'type': 'corridor'}
                },
                2: {
                    '0001' : {'coords': [4.3, 3.1, 1.0], 'type': 'crossway'},
                    '0002' : {'coords': [4.5, 3.3, 1.0], 'type': 'corridor'}
                }
}
print(drones_db[1])
print(len(drones_db[1]))
for id1, data1 in drones_db[1].items():
    print(type(id1))
    print(type(data1))
    

print(drones_db[1]['0001']['coords'])
print(drones_db)
adjacency_matrix = np.array([[0. , 1. ], [1. , 0. ]])
print(adjacency_matrix)

#aggiungere punto 
drones_db[2]['0003'] = {'coords': [3.4, 2.3, 1.0], 'type': 'corridor'}
print(drones_db[2])

def euclidean_distance(point1, point2):
    return np.linalg.norm(np.array(point1) - np.array(point2))

def merge_similar_points(drones_db, drone1_id, drone2_id, threshold=0.5):
    drone1_points = drones_db[drone1_id]
    drone2_points = drones_db[drone2_id]
    
    for id1, data1 in drone1_points.items():
        for id2, data2 in drone2_points.items():
            if euclidean_distance(data1['coords'], data2['coords']) < threshold:
                # Calcola la media delle coordinate
                new_coords = np.mean([data1['coords'], data2['coords']], axis=0).tolist()
                # Aggiorna i punti con le coordinate mediate
                drones_db[drone1_id][id1]['coords'] = new_coords
                drones_db[drone2_id][id2]['coords'] = new_coords
print(drones_db)
merge_similar_points(drones_db, 1, 2, threshold=0.5)
print(drones_db)


{'0001': {'coords': [3.0, 1.8, 1.0], 'type': 'junction'}, '0002': {'coords': [3.3, 2.3, 1.0], 'type': 'corridor'}, '0003': {'coords': [1.0, 1.0, 1.0], 'type': 'corridor'}}
3
<class 'str'>
<class 'dict'>
<class 'str'>
<class 'dict'>
<class 'str'>
<class 'dict'>
[3.0, 1.8, 1.0]
{1: {'0001': {'coords': [3.0, 1.8, 1.0], 'type': 'junction'}, '0002': {'coords': [3.3, 2.3, 1.0], 'type': 'corridor'}, '0003': {'coords': [1.0, 1.0, 1.0], 'type': 'corridor'}}, 2: {'0001': {'coords': [4.3, 3.1, 1.0], 'type': 'crossway'}, '0002': {'coords': [4.5, 3.3, 1.0], 'type': 'corridor'}}}
[[0. 1.]
 [1. 0.]]
{'0001': {'coords': [4.3, 3.1, 1.0], 'type': 'crossway'}, '0002': {'coords': [4.5, 3.3, 1.0], 'type': 'corridor'}, '0003': {'coords': [3.4, 2.3, 1.0], 'type': 'corridor'}}
{1: {'0001': {'coords': [3.0, 1.8, 1.0], 'type': 'junction'}, '0002': {'coords': [3.3, 2.3, 1.0], 'type': 'corridor'}, '0003': {'coords': [1.0, 1.0, 1.0], 'type': 'corridor'}}, 2: {'0001': {'coords': [4.3, 3.1, 1.0], 'type': 'crossway'}

In [13]:
drone_id = 12
point_id = '0008'
custom_id = f"{drone_id:03}_{point_id}"
print(custom_id)

012_0008


In [15]:
def increment_point_id(point_id):
    """Incrementa una stringa di point_id del tipo 'xxxx' di 1"""
    return f'{int(point_id) + 1:04}'

point_id = '0004'
point_id = increment_point_id(point_id)
print(point_id)

0005


In [19]:
def increment_point_id(point_id,quantity):
    """Incrementa una stringa di point_id del tipo 'xxxx' di 1"""
    return f'{int(point_id) + quantity:04}'

point_id = '0004'
point_id = increment_point_id(point_id,0)
print(point_id)

0004


In [20]:
to_remove_drone1=['0001', '0002', '0002', '0003' ]
print(to_remove_drone1)


to_remove_drone1 = set(to_remove_drone1)
print(to_remove_drone1)

['0001', '0002', '0002', '0003']
{'0003', '0001', '0002'}


In [47]:
import numpy as np
def replace_node_in_adjacency_matrix(adjacency_matrix, old_node, new_node):
        """
        Sostituisce un nodo in una matrice di adiacenza con un nuovo nodo, trasferendo tutti gli edge.

        Parameters
        ----------
        adjacency_matrix : np.ndarray
            La matrice di adiacenza.
        old_node : int
            L'indice del nodo da sostituire.
        new_node : int
            L'indice del nuovo nodo.

        Returns
        -------
        np.ndarray
            La nuova matrice di adiacenza con il nodo sostituito.
        """
        num_nodes = adjacency_matrix.shape[0]

        # Creiamo una nuova matrice di adiacenza con una dimensione aumentata di 1
        new_matrix = np.zeros((num_nodes + 1, num_nodes + 1), dtype=int)

        # Copiamo la matrice di adiacenza originale nella nuova matrice
        new_matrix[:num_nodes, :num_nodes] = adjacency_matrix

        # Trasferiamo tutti gli edge dal vecchio nodo al nuovo nodo
        new_matrix[new_node, :-1] = adjacency_matrix[old_node, :]
        new_matrix[:-1, new_node] = adjacency_matrix[:, old_node]

        # Impostiamo a zero la riga e la colonna del vecchio nodo
        new_matrix[old_node, :] = 0
        new_matrix[:, old_node] = 0

        return new_matrix
adjacency_matrix=np.array([[0 ,1 , 0 ,0 , 0 , 0 , 0],
                           [1 ,0 , 1 ,0 , 0 , 0 , 0],
                           [0 ,1 , 0 ,1 , 0 , 0 , 0],
                           [0 ,0 , 1 ,0 , 1 , 0 , 0],
                           [0 ,0 , 0 ,1 , 0 , 1 , 0],
                           [0 ,0 , 0 ,0 , 1 , 0 , 1],
                           [0 ,0 , 0 ,0 , 0 , 1 , 0]])
print(adjacency_matrix)

#FUNCTION SIMULATION
new_node = 7
old_node = 6 
num_nodes = adjacency_matrix.shape[0]
print(num_nodes)
new_matrix = np.zeros((num_nodes + 1, num_nodes + 1), dtype=int)
new_matrix[:num_nodes, :num_nodes] = adjacency_matrix
#print(new_matrix)
new_matrix[new_node, :-1] = adjacency_matrix[old_node, :]
new_matrix[:-1, new_node] = adjacency_matrix[:, old_node]
#print(new_matrix)
new_matrix[old_node, :] = 0
new_matrix[:, old_node] = 0
print(new_matrix)
# current_matrix = replace_node_in_adjacency_matrix(current_matrix,4,7)
# print(current_matrix)
# new_matrix = np.pad(current_matrix, ((0, 1), (0, 1)), mode='constant', constant_values=0)
# print(new_matrix)

[[0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 1 0]
 [0 0 0 0 1 0 1]
 [0 0 0 0 0 1 0]]
7
[[0 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 0 1 0 1 0 0 0]
 [0 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]]


In [49]:
num_nodes=7
for i in range(num_nodes):
    print(i)

0
1
2
3
4
5
6


In [3]:
NUM_DRONES = 5
import numpy as np
IM_IN_A_CORNER = np.array([[False] for j in range(NUM_DRONES)] )
print(IM_IN_A_CORNER)

[[False]
 [False]
 [False]
 [False]
 [False]]


In [11]:
seen_coords = set()
new_coords = tuple(np.array([3.0, 1.8, 1.0]).tolist())
seen_coords.add(new_coords)
new_coords = tuple(np.array([3.3, 2.3, 1.0]).tolist())
seen_coords.add(new_coords)
new_coords = tuple(np.array([1.0, 1.0, 1.0]).tolist())
seen_coords.add(new_coords)
new_coords = tuple(np.array([1.0, 1.0, 1.0]).tolist())

seen_coords.add(new_coords)
print(seen_coords)

new_coords = tuple(np.array([1.0, 1.0, 1.0]).tolist())

if new_coords not in seen_coords:
    print("trovato")
else:
    print("non trovato")


{(3.3, 2.3, 1.0), (1.0, 1.0, 1.0), (3.0, 1.8, 1.0)}
non trovato
