In [1]:
import numpy as np
import pybullet as p

NUM_DRONES = 4
distWallRef = 0.5
SENSOR_ATTR = True
max_range = 3
if SENSOR_ATTR :
    sensor_position =np.zeros((4,3)) 
    print(sensor_position)  # questo è lo zero del mondo
    sensor_direction = np.array([
    [1.0, 0.0, 0.0],  # front
    [0.0, 1.0, 0.0],  # Rx
    [-1.0, 0.0, 0.0],   # behind
    [0.0, -1.0, 0.0],  # Lx
    ])
    rot_mat = np.array([      # rot mat esempio SOTTO come estrarla veramente
    [0.866, -0.5, 0.0],
    [0.5, 0.866, 0.0],
    [0.0, 0.0, 1.0]
    ])
    # rot_mat = np.array(p.getMatrixFromQuaternion(quat[nth_drone, :])).reshape(3, 3)
    sensor_direction = np.dot(sensor_direction,rot_mat)   # (3, 3) * () 
    print(sensor_direction)

    observation = np.array([[max_range,max_range,max_range,max_range] for j in range(NUM_DRONES)] )
    print(observation)

def _sensorsObs():
        # observation = np.array([[max_range,max_range,max_range,max_range] for j in range(NUM_DRONES)] )
        Hit_point = []
        if SENSOR_ATTR:
            for i in range(NUM_DRONES):
                closest_hit = []
                for j in range(NUM_SENSORS) :
                    sensor_position = _getDroneStateVector(i)[0:3]  # piazza il sensore nella posiz attuale
                    from_positions = [sensor_position] * 4
                    
                    to_positions = [sensor_position + sensor_direction * 3 for direction in directions.values()]
                  #  result = p.rayTest(sensor_position, 
                  #                      [sensor_position[0] + max_range[0] * sensor_direction[j][0], 
                  #                      sensor_position[1] + max_range[0] * sensor_direction[j][1], 
                  #                      sensor_position[2] + max_range[0] * sensor_direction[j][2]])
                    result = p.rayTestBatch(from_positions, to_positions)
                    closest_hit.append(result[0])
                        #closest_hit[j][0] = result_list[j][0]
                    # Se c'è un punto di contatto, ottieni la distanza
                    if closest_hit[j][0] != -1:
                        hit_distance = closest_hit[j][2]
                        hit_point = closest_hit[j][3]
                        # Aggiungi la distanza rilevata come osservazione
                        observation[i][j]= hit_distance
                        Hit_point.append(hit_point)
                    else:
                        # Se non ci sono oggetti rilevati, assegna una distanza massima
                        observation[i][j] =  self.max_range
                        Hit_point.append([])
        return observation, Hit_point

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.866 -0.5    0.   ]
 [ 0.5    0.866  0.   ]
 [-0.866  0.5    0.   ]
 [-0.5   -0.866  0.   ]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [8]:
max_range = 3
sensor_position = np.array([0. , 0. , 0.]) # piazza il sensore nella posiz attuale
print(sensor_position)
from_positions = [sensor_position] * 4
print(from_positions)
sensor_direction = [
    [1.0, 0.0, 0.0],  # front
    [0.0, 1.0, 0.0],  # Rx
    [-1.0, 0.0, 0.0],   # behind
    [0.0, -1.0, 0.0],  # Lx
    ]
sensor_direction = np.array(sensor_direction)   # converte in matrice numpy
rot_mat = np.array([      # rot mat esempio SOTTO come estrarla veramente
    [0.866, -0.5, 0.0],
    [0.5, 0.866, 0.0],
    [0.0, 0.0, 1.0]
    ])
    # rot_mat = np.array(p.getMatrixFromQuaternion(quat[nth_drone, :])).reshape(3, 3)
sensor_direction = np.dot(sensor_direction,rot_mat)   # (3, 3) * () 
print(sensor_direction)
from_positions = np.tile(sensor_position, (4, 1))
print(from_positions)
to_positions = np.array([sensor_position + direction * max_range for direction in sensor_direction])
print(to_positions)

[0. 0. 0.]
[array([0., 0., 0.]), array([0., 0., 0.]), array([0., 0., 0.]), array([0., 0., 0.])]
[[ 0.866 -0.5    0.   ]
 [ 0.5    0.866  0.   ]
 [-0.866  0.5    0.   ]
 [-0.5   -0.866  0.   ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 2.598 -1.5    0.   ]
 [ 1.5    2.598  0.   ]
 [-2.598  1.5    0.   ]
 [-1.5   -2.598  0.   ]]


In [16]:
import numpy as np### TEST PRODOTTO RXC ROTAZIONE
sensor_direction = np.array([
    [1.0, 0.0, 0.0],  # front
    [0.0, 1.0, 0.0],  # Rx
    [-1.0, 0.0, 0.0],   # behind
    [0.0, -1.0, 0.0],  # Lx
    ])
rot_mat = np.array([      # rot mat esempio SOTTO come estrarla veramente
    [0.866, -0.5, 0.0],
    [0.5, 0.866, 0.0],
    [0.0, 0.0, 1.0]
    ])
    # rot_mat = np.array(p.getMatrixFromQuaternion(quat[nth_drone, :])).reshape(3, 3)
sensor_direction = np.dot(sensor_direction,rot_mat)   # (3, 3) * ()
print(sensor_direction)

[[ 0.866 -0.5    0.   ]
 [ 0.5    0.866  0.   ]
 [-0.866  0.5    0.   ]
 [-0.5   -0.866  0.   ]]


In [8]:
import numpy as np
a=np.array([ 0 , 0 , 0 ])
print("a=",a)
print(a.shape)
b=np.array([ 0 , 0 , 0 ])
c = np.vstack((a, b))
print("c=",c)
print(c.shape)
d = np.hstack((a, b))
print("d=",d, "fatto male")
print(d.shape)
e = np.hstack((a[:, np.newaxis], b[:, np.newaxis]))
print("e=",e)
print(e.shape)
print("c e e sono uguali solo se il vettore era di 2 valori")

a= [0 0 0]
(3,)
c= [[0 0 0]
 [0 0 0]]
(2, 3)
d= [0 0 0 0 0 0] fatto male
(6,)
e= [[0 0]
 [0 0]
 [0 0]]
(3, 2)
c e e sono uguali solo se il vettore era di 2 valori


In [2]:
import numpy as np
NUM_DRONES = 3
NUM_SENSORS = 4
Hit_point = np.array([[[np.inf , np.inf , np.inf] for j in range(NUM_SENSORS)]for i in range(NUM_DRONES)] )
print(Hit_point)
hit_point = (1.0000000000000002, 0.0, 0.9998298611111112)
print(hit_point)
Hit_point[1][0] = hit_point
print(Hit_point)


[[[inf inf inf]
  [inf inf inf]
  [inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]
  [inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]
  [inf inf inf]
  [inf inf inf]]]
(1.0000000000000002, 0.0, 0.9998298611111112)
[[[       inf        inf        inf]
  [       inf        inf        inf]
  [       inf        inf        inf]
  [       inf        inf        inf]]

 [[1.         0.         0.99982986]
  [       inf        inf        inf]
  [       inf        inf        inf]
  [       inf        inf        inf]]

 [[       inf        inf        inf]
  [       inf        inf        inf]
  [       inf        inf        inf]
  [       inf        inf        inf]]]


In [16]:
import numpy as np
hit_point = (1.0000000000000002, 0.0, 2.9998298611111112)

idx = np.random.choice(len(hit_point), 2, replace=False)
print(idx)
x1, y1 = hit_point[idx[0]][0:1]
x2, y2 = hit_point[idx[1]][0:1]

[0 2]


TypeError: 'float' object is not subscriptable

In [5]:
import numpy as np
rR=1
rF=np.inf
alfa = np.arctan(rF/rR)  #arctan di inf fa pi/2
d = rF * np.cos(alfa)

print(alfa)
print(np.cos(alfa))
print(d)

1.5707963267948966
6.123233995736766e-17
inf


In [12]:
omega= 1
a = []
a.append(omega)
a.append(omega)
print(a)
b = []
np.vstack((b,omega))


[1, 1]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 0 and the array at index 1 has size 1

In [18]:
NUM_DRONES = 4
omega = np.array([[0.] for j in range(NUM_DRONES)])
sWF = [5 , 2]
cw = 0.03
print(omega      )

omega [1] = ([-1*sWF[1]*cw])
print(omega     )

[[0.]
 [0.]
 [0.]
 [0.]]
[[ 0.  ]
 [-0.06]
 [ 0.  ]
 [ 0.  ]]


In [3]:
import numpy as np
CLOUD_POINT = np.empty((3,0))
print(CLOUD_POINT)
print(CLOUD_POINT.shape)

PREV_DIST = np.array([[] for j in range(3)])
print(PREV_DIST)
print(PREV_DIST.shape)
PREV_DIST[2] =  ([0])
print(PREV_DIST)
print(PREV_DIST.shape)

[]
(3, 0)
[]
(3, 0)
[]
(3, 0)


In [27]:
NWdistance = np.inf
SWdistance =  np.inf
distance = min(NWdistance, SWdistance)
print(distance)
if distance == np.inf:
    print("daje")

inf
daje


In [28]:
import numpy as np
distance=np.array([[np.inf , np.inf] for j in range(1)] )
print(distance)

omega1 = np.array([0 , 0])
print(omega1)
print(omega1.shape)


[[inf inf]]
[0 0]
(2,)


In [40]:
Omega = ([3.])
print(Omega)


omega = np.array([[0.] for j in range(3)])
print(omega)
omega[1] = Omega
print(omega)
print(omega[1])


[3.0]
[[0.]
 [0.]
 [0.]]
[[0.]
 [3.]
 [0.]]
[3.]


In [41]:
# forse dovremmo fare così per quando sono liste di valori e non di vettori
Omega = ([3.])
print(Omega)


omega = np.array([0. for j in range(3)])
print(omega)
omega[1] = Omega[0]
print(omega)
print(omega[1])
#print(omega[1][0])

[3.0]
[0. 0. 0.]
[0. 3. 0.]
3.0


In [2]:
s_WF: int = -1
S_WF = np.array([[s_WF] for j in range(3)])
print(S_WF[1][0])
np.arctan(np.inf)

-1


1.5707963267948966

In [1]:
import numpy as np
distance=np.array([ [["droneID"]] , [[ 1. , 1. , 1.] for j in range(10)]  ])
print(distance)



ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [43]:


a = 13
print(a)
a = np.clip(a, -2., 2.)
print(a)
a[2] = np.clip(a[2], -0.15, .15)
print(a)

13
2.0


IndexError: invalid index to scalar variable.

In [1]:
import numpy as np
NUM_DRONES = 3 
wfstatezero_debugger = np.array([[0. , 0. , 0.] for j in range(NUM_DRONES)] )
print(wfstatezero_debugger)
wfstatezero_debugger[1] = [1. , 1. , 1.]
print(wfstatezero_debugger)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]


In [11]:
import numpy as np
cv = 3
vel = np.array([[0. , 0. , 0.] for j in range(5)])
print (vel)
vel [2] = np.dot(  cv , [1. , 0. , 0.] )
print (vel)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [3. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
