In [1]:
import numpy as np
import pybullet as p

NUM_DRONES = 4
distWallRef = 0.5
SENSOR_ATTR = True
max_range = 3
if SENSOR_ATTR :
    sensor_position =np.zeros((4,3)) 
    print(sensor_position)  # questo è lo zero del mondo
    sensor_direction = np.array([
    [1.0, 0.0, 0.0],  # front
    [0.0, 1.0, 0.0],  # Rx
    [-1.0, 0.0, 0.0],   # behind
    [0.0, -1.0, 0.0],  # Lx
    ])
    rot_mat = np.array([      # rot mat esempio SOTTO come estrarla veramente
    [0.866, -0.5, 0.0],
    [0.5, 0.866, 0.0],
    [0.0, 0.0, 1.0]
    ])
    # rot_mat = np.array(p.getMatrixFromQuaternion(quat[nth_drone, :])).reshape(3, 3)
    sensor_direction = np.dot(sensor_direction,rot_mat)   # (3, 3) * () 
    print(sensor_direction)

    observation = np.array([[max_range,max_range,max_range,max_range] for j in range(NUM_DRONES)] )
    print(observation)

def _sensorsObs():
        # observation = np.array([[max_range,max_range,max_range,max_range] for j in range(NUM_DRONES)] )
        Hit_point = []
        if SENSOR_ATTR:
            for i in range(NUM_DRONES):
                closest_hit = []
                for j in range(NUM_SENSORS) :
                    sensor_position = _getDroneStateVector(i)[0:3]  # piazza il sensore nella posiz attuale
                    from_positions = [sensor_position] * 4
                    
                    to_positions = [sensor_position + sensor_direction * 3 for direction in directions.values()]
                  #  result = p.rayTest(sensor_position, 
                  #                      [sensor_position[0] + max_range[0] * sensor_direction[j][0], 
                  #                      sensor_position[1] + max_range[0] * sensor_direction[j][1], 
                  #                      sensor_position[2] + max_range[0] * sensor_direction[j][2]])
                    result = p.rayTestBatch(from_positions, to_positions)
                    closest_hit.append(result[0])
                        #closest_hit[j][0] = result_list[j][0]
                    # Se c'è un punto di contatto, ottieni la distanza
                    if closest_hit[j][0] != -1:
                        hit_distance = closest_hit[j][2]
                        hit_point = closest_hit[j][3]
                        # Aggiungi la distanza rilevata come osservazione
                        observation[i][j]= hit_distance
                        Hit_point.append(hit_point)
                    else:
                        # Se non ci sono oggetti rilevati, assegna una distanza massima
                        observation[i][j] =  self.max_range
                        Hit_point.append([])
        return observation, Hit_point

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.866 -0.5    0.   ]
 [ 0.5    0.866  0.   ]
 [-0.866  0.5    0.   ]
 [-0.5   -0.866  0.   ]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [8]:
max_range = 3
sensor_position = np.array([0. , 0. , 0.]) # piazza il sensore nella posiz attuale
print(sensor_position)
from_positions = [sensor_position] * 4
print(from_positions)
sensor_direction = [
    [1.0, 0.0, 0.0],  # front
    [0.0, 1.0, 0.0],  # Rx
    [-1.0, 0.0, 0.0],   # behind
    [0.0, -1.0, 0.0],  # Lx
    ]
sensor_direction = np.array(sensor_direction)   # converte in matrice numpy
rot_mat = np.array([      # rot mat esempio SOTTO come estrarla veramente
    [0.866, -0.5, 0.0],
    [0.5, 0.866, 0.0],
    [0.0, 0.0, 1.0]
    ])
    # rot_mat = np.array(p.getMatrixFromQuaternion(quat[nth_drone, :])).reshape(3, 3)
sensor_direction = np.dot(sensor_direction,rot_mat)   # (3, 3) * () 
print(sensor_direction)
from_positions = np.tile(sensor_position, (4, 1))
print(from_positions)
to_positions = np.array([sensor_position + direction * max_range for direction in sensor_direction])
print(to_positions)

[0. 0. 0.]
[array([0., 0., 0.]), array([0., 0., 0.]), array([0., 0., 0.]), array([0., 0., 0.])]
[[ 0.866 -0.5    0.   ]
 [ 0.5    0.866  0.   ]
 [-0.866  0.5    0.   ]
 [-0.5   -0.866  0.   ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 2.598 -1.5    0.   ]
 [ 1.5    2.598  0.   ]
 [-2.598  1.5    0.   ]
 [-1.5   -2.598  0.   ]]


In [16]:
import numpy as np### TEST PRODOTTO RXC ROTAZIONE
sensor_direction = np.array([
    [1.0, 0.0, 0.0],  # front
    [0.0, 1.0, 0.0],  # Rx
    [-1.0, 0.0, 0.0],   # behind
    [0.0, -1.0, 0.0],  # Lx
    ])
rot_mat = np.array([      # rot mat esempio SOTTO come estrarla veramente
    [0.866, -0.5, 0.0],
    [0.5, 0.866, 0.0],
    [0.0, 0.0, 1.0]
    ])
    # rot_mat = np.array(p.getMatrixFromQuaternion(quat[nth_drone, :])).reshape(3, 3)
sensor_direction = np.dot(sensor_direction,rot_mat)   # (3, 3) * ()
print(sensor_direction)

[[ 0.866 -0.5    0.   ]
 [ 0.5    0.866  0.   ]
 [-0.866  0.5    0.   ]
 [-0.5   -0.866  0.   ]]


In [8]:
import numpy as np
a=np.array([ 0 , 0 , 0 ])
print("a=",a)
print(a.shape)
b=np.array([ 0 , 0 , 0 ])
c = np.vstack((a, b))
print("c=",c)
print(c.shape)
d = np.hstack((a, b))
print("d=",d, "fatto male")
print(d.shape)
e = np.hstack((a[:, np.newaxis], b[:, np.newaxis]))
print("e=",e)
print(e.shape)
print("c e e sono uguali solo se il vettore era di 2 valori")

a= [0 0 0]
(3,)
c= [[0 0 0]
 [0 0 0]]
(2, 3)
d= [0 0 0 0 0 0] fatto male
(6,)
e= [[0 0]
 [0 0]
 [0 0]]
(3, 2)
c e e sono uguali solo se il vettore era di 2 valori


In [12]:
import numpy as np
NUM_DRONES = 3
NUM_SENSORS = 4
Hit_point = np.array([[[np.inf , 0.0 , 0.0] for j in range(NUM_SENSORS)]for i in range(NUM_DRONES)] )
print(Hit_point)
hit_point = (1.0000000000000002, 0.0, 0.9998298611111112)
print(hit_point)
Hit_point[1][0] = hit_point
print(Hit_point)


[[[inf  0.  0.]
  [inf  0.  0.]
  [inf  0.  0.]
  [inf  0.  0.]]

 [[inf  0.  0.]
  [inf  0.  0.]
  [inf  0.  0.]
  [inf  0.  0.]]

 [[inf  0.  0.]
  [inf  0.  0.]
  [inf  0.  0.]
  [inf  0.  0.]]]
(1.0000000000000002, 0.0, 0.9998298611111112)
[[[       inf 0.         0.        ]
  [       inf 0.         0.        ]
  [       inf 0.         0.        ]
  [       inf 0.         0.        ]]

 [[1.         0.         0.99982986]
  [       inf 0.         0.        ]
  [       inf 0.         0.        ]
  [       inf 0.         0.        ]]

 [[       inf 0.         0.        ]
  [       inf 0.         0.        ]
  [       inf 0.         0.        ]
  [       inf 0.         0.        ]]]
